create table if not exists public.business_enquiries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  city text not null,
  requirement text,
  cart_items jsonb not null default '[]'::jsonb,
  total_amount numeric(12, 2) not null default 0,
  source text not null default 'rasoiworks-website'
);

alter table public.business_enquiries enable row level security;

drop policy if exists "Anyone can create business enquiries" on public.business_enquiries;
create policy "Anyone can create business enquiries"
  on public.business_enquiries
  for insert
  to anon
  with check (true);

drop policy if exists "Authenticated users can read business enquiries" on public.business_enquiries;
create policy "Authenticated users can read business enquiries"
  on public.business_enquiries
  for select
  to authenticated
  using (true);
