create table if not exists public.customer_orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null check (char_length(name) between 2 and 120),
  email text not null check (email ~* '^[^@[:space:]]+@[^@[:space:]]+[.][^@[:space:]]+$'),
  phone text not null check (phone ~ '^[0-9+() -]{8,20}$'),
  city text not null check (char_length(city) between 2 and 80),
  address text not null check (char_length(address) between 10 and 500),
  requirement text check (requirement is null or char_length(requirement) <= 1200),
  order_items jsonb not null default '[]'::jsonb check (jsonb_typeof(order_items) = 'array'),
  total_amount numeric(12, 2) not null default 0 check (total_amount >= 0),
  source text not null default 'surf-soap-india-website' check (source = 'surf-soap-india-website')
);

alter table public.customer_orders enable row level security;

grant insert on public.customer_orders to anon;
grant usage, select on sequence public.customer_orders_id_seq to anon;

drop policy if exists "Anyone can create customer orders" on public.customer_orders;
create policy "Anyone can create customer orders"
  on public.customer_orders
  for insert
  to anon
  with check (
    source = 'surf-soap-india-website'
    and total_amount >= 0
    and jsonb_typeof(order_items) = 'array'
  );
